function highpass_filter_generatehdl(filtobj)
%  HIGHPASS_FILTER_GENERATEHDL   Function to generate HDL for filter object.
%  Generated by MATLAB(R) 8.1 and the Filter Design HDL Coder 2.9.3.
%  Generated on: 2013-12-24 19:42:35
%  -------------------------------------------------------------
%  HDL Code Generation Options:
%  FIRAdderStyle: tree
%  ClockEnableInputPort: clkena_i
%  ClockInputPort: clk_i
%  ResetInputPort: nrst_i
%  TargetDirectory: /home/egor
%  AddPipelineRegisters: on
%  Name: highpass_filter
%  TargetLanguage: Verilog
%  TestBenchName: highpass_filter_tb
%  TestBenchStimulus: impulse step ramp chirp noise 
%  GenerateHDLTestbench: on
% 
%  Filter Settings:
%  Discrete-Time FIR Filter (real)
%  -------------------------------
%  Filter Structure  : Direct-Form FIR
%  Filter Length     : 33
%  Stable            : Yes
%  Linear Phase      : No

%  -------------------------------------------------------------

% Generating HDL code
generatehdl(filtobj, 'FIRAdderStyle', 'tree',... 
               'ClockEnableInputPort', 'clkena_i',... 
               'ClockInputPort', 'clk_i',... 
               'ResetInputPort', 'nrst_i',... 
               'TargetDirectory', '/home/egor',... 
               'AddPipelineRegisters', 'on',... 
               'Name', 'highpass_filter',... 
               'TargetLanguage', 'Verilog',... 
               'TestBenchName', 'highpass_filter_tb',... 
               'TestBenchStimulus',  {'impulse', 'step', 'ramp', 'chirp', 'noise'},... 
               'GenerateHDLTestbench', 'on');

% [EOF]
